a. http://www.cnblogs.com/fsjohnhuang/p/7685144.html  前端魔法堂——异常不仅仅是try/catch
b. 



1. 前端异常，导致不会导致js引擎崩溃，但可能让当前执行的任务终止

2. 所有异常类 继承自 Error ，标准方法、属性如下
    @prop {String} name - 异常名称
    @prop {String} message - 供人类阅读的异常信息
    @prop {Function} constructor - 类型构造器
    @method toString():String - 输出异常信息

3.  异常，浏览器实现的其他属性
    @prop {String} fileName - 异常发生的脚本URI
    @prop {number} lineNumber - 异常发生的行号
    @prop {number} columnNumber - 异常发生的列号
    @prop {String} stack - 异常发生时的调用栈信息，IE10及以上才支持
    @method toSource():String - 异常发生的脚本内容

4. 异常类型，常见如 
    ReferenceError，当引用未声明的变量时发生
    SyntaxError，解析时发生语法错误
    TypeError，当值不是所期待的类型时，常见于对象属性方法调用，null.f()也报这个错
    URIError，当传递一个非法的URI给全局URI处理函数时发生，如decodeURIComponent('%')，即decodeURIComponent，decodeURI,encodeURIComponent，encodeURI


5. 自定义异常类型

    function MyError(message, fileName, lineNumber){
    if (this instanceof MyError);else return new MyError(message, fileName, lineNumber)
        this.message = message || ""
        if (fileName){ this.fileName = fileName }
        if (lineNumber){ this.lineNumber = lineNumber }
    }

    var proto = MyError.prototype = Object.create(Error.prototype)
    proto.name = "MyError"
    proto.constructor = MyError


6. 同步代码，运行时异常捕捉 => try - catch
    a. "同步代码"就是说无法获取如setTimeout、Promise等异步代码的异常，也就是说try/catch仅能捕获当前任务的异常，setTimeout等异步代码是在下一个EventLoop中执行 
    b. "运行时异常"是指非SyntaxError，也就是语法错误是无法捕获的，因为在解析JavaScript源码时就已经报错
    c. throw 可以跑出任意类型的数据，但最好抛出Error或其子类的实例，因为异常发生时提供信息越全越好，越容易追踪定位重现问题

7. window.onerror => Javascript 顶层异常处理入口，通过它除了try/catch能捕获的异常外，还可以捕获setTimeout等的异步代码异常、语法错误， 函数如参如下
    @description window.onerror处理函数
    @param {string} message - 异常信息"
    @param {string} source  - 发生异常的脚本的URI
    @param {number} lineno  - 发生异常的脚本行号
    @param {number} colno   - 发生异常的脚本列号
    @param {?Error} error   - Error实例，Safari和IE10中没有这个实参

    @DESC ： 只有onerror函数返回true时，异常才不会继续向上抛

8. onerror 无法捕获所有异常
    1. Chrome中对于跨域脚本所报的异常，虽然onerror能够捕获，但统一报Script Error。若要得到正确的错误信息，则要配置跨域资源共享CORS才可以。
    2. window.onerror实际上采用的事件冒泡的机制捕获异常，并且在冒泡(bubble)阶段时才触发，因此像网络请求异常这些不会冒泡的异常是无法捕获的。
    3. Promise.reject产生的未被catch的异常，window.onerror也是无能为力。

9. Promise 异常捕获
    a. Promise实例的初始化状态是pending，而发生异常时则为rejected，而导致状态从pending转变为rejected的操作有

        调用Promise.reject类方法
        在工厂方法中调用reject方法
        在工厂方法或then回调函数中抛异常

        当Promise实例从pending转变为rejected时，和之前谈论到异常一样，要么被捕获处理，要么继续抛出直到成为Uncaught(in promise) Error为止


```javascript
    // 方式1
    Promise.reject("anything you want")

    // 方式2
    new Promise(function(resolve, reject) { reject("anything you want") })

    // 方式3
    new Promise(function{ throw "anything you want" })
    new Promise(function(r) { r(Error("anything you want" ) }).then(function(e) { throw e })

```

    b. 通过 new Promise(function() {}).catch(function(e){}) 捕捉错误
    c. 通过window的unhandledrejection事件捕获异常（专属于Promise的顶层异常处理）

```javascript

    window.addEventListener("unhandledrejection", function(e){
        // Event新增属性
        // @prop {Promise} promise - 状态为rejected的Promise实例
        // @prop {String|Object} reason - 异常信息或rejected的内容

        // 会阻止异常继续抛出，不让Uncaught(in promise) Error产生
        e.preventDefault()
    })

```


10. 404 等网络请求如何监控 

```javascript
    window.addEventListener("error", function(e){   // ????
        // Do something
        console.log(e.bubbles) // 回显false
    }, true)
```



跨域错误 Script error 浏览器同源策略导致

    1. iframe

        同源： 根据 iframe onerror事件处理
        非第三方: 通过iframe通信

    2. 将在资源放置在cdn导致的跨域问题
    
        浏览器： <script type="text/javascript" src="https://og6593g2z.qnssl.com/scripterror.js" crossorigin="anonymous"></script>
        后台设置： allow-origin: www.XXX.com






JavaScript执行错误
资源加载错误  resourceError 404
HTTP请求错误  httpError
unhandledrejection，即未catch处理的Promise错误
WebSockect错误


1. 监控用户 点击，页面跳转，网络请求
2. 重写console对象监控浏览器控制台的打印信息



window.onerror = function(errorMessage, scriptURI, lineNumber, columnNumber, error){
    console.log(errorMessage);
    console.log(scriptURI);
    console.log(lineNumber);
    console.log(columnNumber);
    console.log(error);
}

    



js执行错误
{
    "notifierVersion": "0.2.0",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:54.0) Gecko/20100101 Firefox/54.0",
    "locale": "zh",
    "url": "http://localhost:4000",
    "title": "Test",
    "apiKey": "API-KEY",
    "name": "ReferenceError",
    "time": 1502863944724,
    "message": "Uncaught ReferenceError: aler is not defined",
    "fileName": "http://localhost:4000/test.js",
    "lineNumber": 1,
    "columnNumber": 1,
    "stacktrace": "@http://localhost:4000/test.js:1:1\n",
    "type": "uncaught",
    "severity": "error"
}


resourceError
{
    "notifierVersion": "0.2.0",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:54.0) Gecko/20100101 Firefox/54.0",
    "locale": "zh",
    "url": "https://www.fundebug.com",
    "title": "Test",
    "apiKey": "API-KEY",
    "time": 1502864167717,
    "type": "resourceError",
    "target": {
        "outerHTML": "<img src=\"test.jpg\">",
        "src": "https://www.fundebug.com/test.jpg",
        "tagName": "IMG",
        "id": "",
        "className": "",
        "name": "jpg",
        "XPath": "/html/body/img[1]",
        "selector": "HTML > BODY:nth-child(2) > IMG:nth-child(2)",
        "status": 404,
        "statusText": "Not Found"
    }
}


httpError: 
{
    "notifierVersion": "0.2.0",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:54.0) Gecko/20100101 Firefox/54.0",
    "locale": "zh",
    "url": "http://localhost:4000",
    "title": "Test",
    "apiKey": "API-KEY",
    "time": 1502864518516,
    "type": "httpError",
    "req": {
        "method": "POST",
        "url": "https://www.fundebug.com/login"
    },
    "res": {
        "status": 403,
        "statusText": "Forbidden",
        "response": "{\"error\":\"wrong password\"}"
    }
}



